spring:
  redis:
    host: 192.168.28.128
    port: 6379
    password: admin
    lettuce:
      pool:
        max-active: 8 #最大连接
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        max-wait: 100ms #连接等待时间
  datasource:
    name: schbusrez  #数据库名
    url: jdbc:mysql://localhost:3306/schbusrez?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true #url
    username: root  #用户名
    password: qq147211xwl  #密码
    driver-class-name: com.mysql.jdbc.Driver #数据库链接驱动
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    enabled: true
    servlet:
      content-type: text/html
    cache: false
    check-template-location: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    favicon:
      enabled: false
mybatis:
  mapper-locations: classpath:*/mapper/*Mapper.xml
  type-aliases-package: com.example.schbusrez.bean
  configuration:
    map-underscore-to-camel-case: true
